name: Terraform

env:
  working-directry: ./user

on: 
    workflow_dispatch:



jobs:
  terraform:
    runs-on: ubuntu-latest
    env: 
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_SESSION_TOKEN:  ${{secrets.AWS_SESSION_TOKEN}}
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo this is code for terraform file

      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v2

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ${{env.working-directry}}
      
      - name: Terraform destroy
        id: destroy
        run: terraform destroy -auto-approve
        working-directory: ${{env.working-directry}}